job_research_task:
  description: >
    Analyze the job posting at {job_url} and create a detailed report about the requirements,
    responsibilities, and company culture. Make sure to identify and extract the company name
    from the job posting. Focus on key technical skills, experience requirements, and any
    unique aspects of the role that would be important for tailoring a resume.
  expected_output: >
    A comprehensive analysis of the job posting including:
    - Company brief description
    - Date of the job posting
    - Job job_url
    - If is is remote, on-site or hybrid
    - Country
    - Company brief description
    - Technical skills required
    - Experience requirements
    - Key responsibilities
    - Any unique or standout requirements
  agent: researcher

profile_task:
  description: >
    Analyze the professional profile in full_profile.md and create a detailed report
    highlighting key skills, experiences, and achievements that could be relevant
    for the job researched.
  expected_output: >
    A detailed analysis of the professional profile including:
    1. Key technical skills and proficiency levels
    2. Notable projects and achievements
    3. Areas of expertise
    4. Professional experience highlights
    5. Educational background and certifications
  agent: profiler

evaluate_profile_fit_task:
  description: >
    Based on the detailed job analysis and the candidate's professional profile analysis,
    evaluate how well the professional's skills, experience, and background match the job requirements.
    Provide a concise fit score from 1 to 5, where 1 is a poor match and 5 is an excellent match.
    Also, provide a brief, actionable explanation for the score, highlighting the main strengths
    that align with the job and any significant gaps or areas for improvement.
  expected_output: >
    A clear assessment of the profile-to-job fit, structured as follows:
    - **Fit Score (1-5):** [Your numerical score, e.g., 4]
    - **Explanation:** [A concise, bullet-point explanation (max 3-4 points) detailing the key reasons
                      for this score. Focus on direct matches and critical mismatches between the
                      profile and the job requirements, suggesting concrete areas for resume/cover letter
                      tailoring or skill development.]
  agent: evaluator

format_output_task:
  description: >
    Synthesize all the gathered job information, candidate profile analysis, and the compatibility score
    into a structured JobDetails object. This task ensures all fields of the JobDetails model are correctly
    extracted and formatted from the prior task outputs.
    
    **CRITICAL INSTRUCTIONS for 'work_arrangement' and 'specific_location' fields:**
    - For 'work_arrangement': You MUST categorize the job as either 'Remote', 'Hybrid', or 'On-site'.
      Prioritize explicit mentions in the job description. If not explicitly stated, infer based on job context
      and company information.
      
    - For 'specific_location': This field MUST always be populated with the primary geographic location associated
      with the job or the company's headquarters.
      * If the job is 'Hybrid' or 'On-site', extract the most specific geographic location (e.g., 'São Paulo, Brazil', 'Seattle, WA, USA').
      * If the job is 'Remote', identify the company's main headquarters location or the country where the company is primarily based.
          For example, if a remote job is offered by a company based in New York, the 'specific_location' should be 'New York, NY, USA'.
          If a remote job is global and no specific company base is mentioned, try to infer the company's country based on its website or other details.
          If absolutely no location can be inferred, then state "Not specified".
          
    The final output must be a single, valid JSON object that strictly adheres to the JobDetails Pydantic schema.
    
  expected_output: >
    A single JSON object representing the JobDetails Pydantic model for the current job posting,
    with a clear 'work_arrangement' and a consistently filled 'specific_location'.
    Example for Hybrid/On-site:
    {
      "company_name": "Truveta",
      "job_title": "Product Manager",
      "job_description": "Truveta is the world’s first health provider-led data platform...",
      "work_arrangement": "Hybrid",
      "specific_location": "Seattle, WA, USA", # Localização específica para híbrido/presencial
      "compatibility_score": 3,
      "date_posted": "Not explicitly mentioned",
      "current_date": "2025-07-01T09:30:01.000000",
      "link": "https://job-boards.greenhouse.io/truveta/jobs/5563344004"
    }
    Example for Remote (with company HQ location):
    {
      "company_name": "Nutrislice",
      "job_title": "Technical Product Manager",
      "job_description": "Nutrislice is a technology-driven company focused on improving food experiences...",
      "work_arrangement": "Remote",
      "specific_location": "Denver, CO, USA", # Exemplo de HQ da Nutrislice, mesmo sendo vaga remota
      "compatibility_score": 4,
      "date_posted": "Not specified",
      "current_date": "2025-07-01T09:30:01.000000",
      "link": "https://jobs.gem.com/nutrislice/am9icG9zdDq-Vjz3z4iPR98Qh_HAkkkC?..."
    }
    Example for Remote (no specific HQ, only country inferred):
    {
      "company_name": "GlobalTech",
      "job_title": "Remote Engineer",
      "job_description": "Join our global remote team...",
      "work_arrangement": "Remote",
      "specific_location": "United States", # Exemplo de apenas país se HQ for vaga ou global
      "compatibility_score": 5,
      "date_posted": "2025-06-25",
      "current_date": "2025-07-01T09:30:01.000000",
      "link": "https://globaltech.com/jobs/remote-engineer"
    }
  agent: output_formatter
